### ISSUE TITLE
感谢分享! 就是注释有点少, 读起来有些吃力

### ISSUE THREAD

**Issue by doterlin** [Dennic/SimpleMap-wx#3]
不知道楼主有没有时间加上注释, 各个类和工具方法

**Comment by Dennic** [comment]
这个项目有点老了，我抽空加一些关键方法注释吧。
大家有兴趣的话可以fork去用小程序新出的自定义组件重写一下。

**Comment by doterlin** [comment]
> 这个项目有点老了，我抽空加一些关键方法注释吧。
> 大家有兴趣的话可以fork去用小程序新出的自定义组件重写一下。

好的 多谢

**Comment by doterlin** [comment]
楼主是个大神啊  越看越觉得这实现逻辑挺复杂, 但代码处理的挺好.
